const goods = [
    {
      name: 'Наушники SoundBeats Pro',
      photo: './src/assets/headphones.jpeg',
      text: 'SoundBeats Pro - беспроводные наушники с отличным звуком и долгим временем работы.',
      date: new Date(),
      address: 'Аудиофон, ул. Музыкальная 5',
      owner: 'SoundTech',
      price: '134',
      id: 1,
    },
    {
      name: 'Умные часы SmartWatch X',
      photo: './src/assets/smartwatch.png',
      text: 'SmartWatch X - стильные и функциональные умные часы для активного образа жизни.',
      date: new Date(),
      address: 'ГаджетМаг, пр. Технологический 8',
      owner: 'Gadget Corp.',
      price: '314',
      id: 2,
    },
    {
      name: 'Фитнес-трекер FitPro Plus',
      photo: './src/assets/fitness-tracker.jpg',
      text: 'FitPro Plus - умный фитнес-трекер с множеством функций для отслеживания активности.',
      date: new Date(),
      address: 'СпортЛайн, ул. Фитнесовая 3',
      owner: 'FitnessTech',
      price: '534',
      id: 3,
    },
    {
      name: 'Планшет TabMaster 10',
      photo: './src/assets/tablet.jpg',
      text: 'TabMaster 10 - мощный планшет с качественным дисплеем и быстрым процессором.',
      date: new Date(),
      address: 'ГаджетХаб, ул. Планшетная 12',
      owner: 'TabTech',
      price: '343',
      id: 4,
    },
    {
      name: 'Фотоаппарат LensPro 2000',
      photo: './src/assets/photoapparat.jpg',
      text: 'LensPro 2000 - профессиональный фотоаппарат с широким диапазоном настроек и высоким разрешением.',
      date: new Date(),
      address: 'ФотоМагия, пр. Фотографический 7',
      owner: 'PhotoTech',
      price: '567',
      id: 5,
    },
    {
      name: 'Видеокамера CinemaVision X',
      photo: './src/assets/videocam.jpg',
      text: 'CinemaVision X - компактная видеокамера с возможностью съемки в высоком разрешении.',
      date: new Date(),
      address: 'ВидеоСалон, ул. Кинематографическая 9',
      owner: 'VideoTech',
      price: '126',
      id: 6,
    },
    {
      name: 'Игровая консоль GameBox One',
      photo: './src/assets/gamestation.jpg',
      text: 'GameBox One - игровая консоль нового поколения с широким выбором игр и возможностью стриминга.',
      date: new Date(),
      address: 'Игровой Мир, ул. Геймерская 6',
      owner: 'GameTech',
      price: '754',
      id: 7,
    }
  ];
  
  export default goods;
  